// Generated by tools/golden — do not edit.
// Regenerate with `cargo run --release` in tools/golden.

//! Golden fixtures, one module per vector family.

pub mod aabb;
pub mod aabb_overlap;
pub mod clip2d;
pub mod contact_manifolds;
pub mod integration_parameters;
pub mod mass_properties;
pub mod point_projection;
pub mod pose2;
pub mod ray_casts;
pub mod sat2d;
pub mod scenes;
pub mod segment_segment;
pub mod sleep_impact;
