// Generated by tools/golden — do not edit.
// Regenerate with `cargo run --release` in tools/golden.

//! Golden fixtures, one module per vector family.

pub mod aabb;
pub mod aabb_overlap;
pub mod ccd_scenes;
pub mod character_moves;
pub mod clip2d;
pub mod composite_aabbs;
pub mod composite_contacts;
pub mod composite_pairs;
pub mod composite_points;
pub mod composite_rays;
pub mod composite_scenes;
pub mod composite_shapes;
pub mod compound_contacts;
pub mod compound_mass;
pub mod compound_pairs;
pub mod compound_points;
pub mod compound_rays;
pub mod compound_scenes;
pub mod compound_shapes;
pub mod contact_manifolds;
pub mod frozen_parry030;
pub mod geometry_utils;
pub mod integration_parameters;
pub mod intersection_tests;
pub mod level_scenes;
pub mod mass_properties;
pub mod nonlinear_shape_casts;
pub mod pid_corrections;
pub mod point_projection;
pub mod polygon_aabb;
pub mod polygon_contacts;
pub mod polygon_mass;
pub mod polygon_point;
pub mod polygon_ray;
pub mod pose2;
pub mod ray_casts;
pub mod round_shape_contacts;
pub mod sat2d;
pub mod scenes;
pub mod segment_segment;
pub mod sensor_trigger;
pub mod sh1_aabb;
pub mod sh1_mass;
pub mod sh1_points;
pub mod sh1_rays;
pub mod shape_casts;
pub mod shape_queries;
pub mod sleep_impact;
pub mod sweep_toi;
pub mod tilted_landing;
pub mod triangle_contacts;
