// Generated by tools/golden — do not edit.
// Regenerate with `cargo run --release` in tools/golden.

//! Golden fixtures, one module per vector family.

pub mod aabb;
pub mod contact_manifolds;
pub mod integration_parameters;
pub mod mass_properties;
