[package]
name = "rapier_core"
description = "Dimension-agnostic data structures of rapier-cairo: handles, arena, union-find, interaction groups."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fixed.workspace = true

[dev-dependencies]
rapier_golden = { path = "../rapier_golden" }
snforge_std.workspace = true
assert_macros.workspace = true
rapier_testing = { path = "../rapier_testing" }

[tool]
fmt.workspace = true
scarb.workspace = true
snforge.workspace = true
