//! Cairo emitter of the `geometry_utils` family (PX3). The case record is flat (see
//! `crate::geometry_utils`): a list of raw `i64` for the inputs and one for the outputs, so the
//! module carries its own tiny type instead of extending the hand-written `types.cairo`.

use super::load;
use serde_json::Value;
use std::path::Path;

fn scalar(v: &Value) -> String {
    if let Some(raw) = v.get("raw") {
        raw.as_i64().unwrap().to_string()
    } else {
        v["int"].as_i64().unwrap().to_string()
    }
}

fn list(v: &Value) -> String {
    let items: Vec<String> = v.as_array().unwrap().iter().map(scalar).collect();
    format!("array![{}].span()", items.join(", "))
}

pub fn generate(vectors: &Path) -> String {
    let json = load(vectors, "geometry_utils.json");
    let mut out = String::from(
        "// Generated by tools/golden from tools/golden/vectors/geometry_utils.json — do not edit.\n\
         // Regenerate with `cargo run --release` in tools/golden.\n\n\
         //! Parry geometry utilities off the step path (PX3): `Aabb` clipping and splitting,\n\
         //! line-line closest points, the support-map projection, `Segment` splits, scaled shapes,\n\
         //! the bounding-sphere queries and the polygonal-feature contacts.\n\
         //!\n\
         //! A case is two flat lists of raw `i64`: Q32.32 reals and plain integers (flags, counts,\n\
         //! sides, tags), in the layout documented in `tools/golden/src/geometry_utils.rs`.\n\n\
         /// One case: `tol` is the comparison band of the reals in ulps (`0` = exact); integers\n\
         /// are always compared exactly.\n\
         #[derive(Copy, Drop)]\n\
         pub struct UtilCase {\n    pub id: felt252,\n    pub tol: i64,\n    pub input: Span<i64>,\n    pub output: Span<i64>,\n}\n",
    );
    let cases = json["cases"].as_array().unwrap();
    let mut funcs: Vec<&str> = Vec::new();
    for c in cases {
        let f = c["fn"].as_str().unwrap();
        if !funcs.contains(&f) {
            funcs.push(f);
        }
    }
    for f in funcs {
        out.push_str(&format!("\npub fn {f}() -> Array<UtilCase> {{\n    array![\n"));
        for c in cases.iter().filter(|c| c["fn"] == f) {
            let id = c["id"].as_str().unwrap().split('/').nth(1).unwrap();
            assert!(id.len() <= super::MAX_SHORT_STRING, "case name {id} too long");
            out.push_str(&format!(
                "        UtilCase {{ id: '{id}', tol: {}, input: {}, output: {} }},\n",
                c["tol"].as_i64().unwrap(),
                list(&c["in"]),
                list(&c["out"]),
            ));
        }
        out.push_str("    ]\n}\n");
    }
    out
}
