#!/usr/bin/env python3
"""Gas snapshot tooling for rapier.cairo.

Every unit test doubles as a gas probe: snforge reports the Sierra gas consumed by
each test, this script records those figures in `.gas-snapshot` and detects drift.

Usage:
    scripts/gas.py snapshot            # run the tests and (re)write .gas-snapshot
    scripts/gas.py check               # run the tests and fail if gas differs from .gas-snapshot
    scripts/gas.py diff                # run the tests and print a Markdown delta table (never fails)
    scripts/gas.py rank <prefix>       # rank snapshot entries under a module prefix (cheapest first)

Common options:
    --from-log FILE    parse an existing `snforge test` log instead of running the tests
    --filter PATTERN   only run / compare tests whose name contains PATTERN

Only the Python standard library is used so the script runs anywhere CI does.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / ".gas-snapshot"
PASS_RE = re.compile(r"^\[PASS\]\s+(\S+)\s+\(.*?l2_gas:\s*~?(\d+)\)")
FAIL_RE = re.compile(r"^\[FAIL\]\s+(\S+)")
SNFORGE = ["snforge", "test", "--workspace", "--tracked-resource", "sierra-gas"]


def run_tests(pattern: str | None) -> str:
    cmd = SNFORGE + ([pattern] if pattern else [])
    proc = subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        sys.stdout.write(proc.stdout)
        sys.exit(f"error: `{' '.join(cmd)}` exited with {proc.returncode}")
    return proc.stdout


def parse(log: str) -> dict[str, int]:
    gas: dict[str, int] = {}
    failed = []
    for line in log.splitlines():
        line = line.strip()
        if m := PASS_RE.match(line):
            gas[m.group(1)] = int(m.group(2))
        elif m := FAIL_RE.match(line):
            failed.append(m.group(1))
    if failed:
        sys.exit("error: failing tests: " + ", ".join(failed))
    return gas


def load_snapshot() -> dict[str, int]:
    if not SNAPSHOT.exists():
        return {}
    entries = {}
    for line in SNAPSHOT.read_text().splitlines():
        if line and not line.startswith("#"):
            name, value = line.rsplit(" ", 1)
            entries[name] = int(value)
    return entries


def write_snapshot(gas: dict[str, int]) -> None:
    header = "# Sierra gas per test, generated by `scripts/gas.py snapshot`. Do not edit by hand.\n"
    SNAPSHOT.write_text(header + "".join(f"{name} {gas[name]}\n" for name in sorted(gas)))


def delta_rows(old: dict[str, int], new: dict[str, int]) -> list[tuple[str, str, str, str]]:
    rows = []
    for name in sorted(old.keys() | new.keys()):
        before, after = old.get(name), new.get(name)
        if before == after:
            continue
        if before is None:
            rows.append((name, "-", str(after), "new"))
        elif after is None:
            rows.append((name, str(before), "-", "removed"))
        else:
            pct = (after - before) / before * 100 if before else 0.0
            rows.append((name, str(before), str(after), f"{after - before:+d} ({pct:+.2f}%)"))
    return rows


def print_table(rows: list[tuple[str, ...]], headers: tuple[str, ...]) -> None:
    print("| " + " | ".join(headers) + " |")
    print("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        print("| " + " | ".join(row) + " |")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["snapshot", "check", "diff", "rank"])
    parser.add_argument("prefix", nargs="?", help="module prefix for `rank`")
    parser.add_argument("--from-log", type=Path)
    parser.add_argument("--filter")
    args = parser.parse_args()

    if args.command == "rank":
        entries = {k: v for k, v in load_snapshot().items() if (args.prefix or "") in k}
        ranked = sorted(entries.items(), key=lambda kv: kv[1])
        print_table([(name, str(value)) for name, value in ranked], ("test", "l2_gas"))
        return

    log = args.from_log.read_text() if args.from_log else run_tests(args.filter)
    new = parse(log)
    if not new:
        sys.exit("error: no test result found in snforge output")
    old = load_snapshot()
    if args.filter:
        old = {k: v for k, v in old.items() if args.filter in k}

    if args.command == "snapshot":
        if args.filter:
            new = {**load_snapshot(), **new}
        write_snapshot(new)
        print(f"wrote {len(new)} entries to {SNAPSHOT.relative_to(ROOT)}")
        return

    rows = delta_rows(old, new)
    if rows:
        print_table(rows, ("test", "before", "after", "delta"))
    else:
        print(f"gas snapshot up to date ({len(new)} tests)")
    if args.command == "check" and rows:
        sys.exit("error: gas usage drifted from .gas-snapshot; run `scripts/gas.py snapshot` and commit the result")


if __name__ == "__main__":
    main()
