#!/usr/bin/env python3
"""Gas snapshot tooling for rapier.cairo.

Every unit test doubles as a gas probe: snforge reports the Sierra gas consumed by each test and
this script records those figures under `gas/<crate>/<module>.snap`, one file per top-level
module, so that parallel branches working on different modules never touch the same snapshot.

Usage:
    scripts/gas.py snapshot [--filter M]  # run the tests and (re)write the snapshot files
    scripts/gas.py check                  # run the tests and fail if gas differs from the snapshots
    scripts/gas.py diff                   # run the tests and print a Markdown delta table (never fails)
    scripts/gas.py rank <prefix>          # rank snapshot entries under a test-name prefix (cheapest first)

Options:
    --from-log FILE    parse an existing `snforge test` log instead of running the tests
    --filter PATTERN   only run / compare / rewrite tests whose name contains PATTERN; with
                       `snapshot`, only the files of modules that appear in the run are rewritten

A test `crate::module::...::name` belongs to `gas/crate/module.snap`; tests declared directly in
`lib.cairo` (`crate::tests::name`) go to `gas/crate/lib.snap`; children of a `SPLIT_MODULES` parent
get `gas/crate/module.child.snap`. Fuzz tests are not recorded (their
gas is a distribution). Only the Python standard library is used so the script runs anywhere CI does.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GAS_DIR = ROOT / "gas"
PASS_RE = re.compile(r"^\[PASS\]\s+(\S+)\s+\(.*?l2_gas:\s*~?(\d+)\)")
FAIL_RE = re.compile(r"^\[FAIL\]\s+(\S+)")
SNFORGE = ["snforge", "test", "--workspace", "--tracked-resource", "sierra-gas"]
HEADER = "# Sierra gas per test, generated by `scripts/gas.py snapshot`. Do not edit by hand.\n"


# Parent modules whose children are written by parallel work packages: one file per child
# (`gas/<crate>/<module>.<child>.snap`) so that those branches never touch a common snapshot.
SPLIT_MODULES = {("rapier_geometry2d", "contact_generators")}


def module_of(test: str) -> tuple[str, str]:
    parts = test.split("::")
    crate = parts[0]
    module = parts[1] if len(parts) > 2 and parts[1] != "tests" else "lib"
    if (crate, module) in SPLIT_MODULES and len(parts) > 3 and parts[2] != "tests":
        module = f"{module}.{parts[2]}"
    return crate, module


def run_tests(pattern: str | None) -> str:
    cmd = SNFORGE + ([pattern] if pattern else [])
    proc = subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        sys.stdout.write(proc.stdout)
        sys.exit(f"error: `{' '.join(cmd)}` exited with {proc.returncode}")
    return proc.stdout


def parse(log: str) -> dict[str, int]:
    gas: dict[str, int] = {}
    failed = []
    for line in log.splitlines():
        line = line.strip()
        if m := PASS_RE.match(line):
            gas[m.group(1)] = int(m.group(2))
        elif m := FAIL_RE.match(line):
            failed.append(m.group(1))
    if failed:
        sys.exit("error: failing tests: " + ", ".join(failed))
    return gas


def load_snapshot() -> dict[str, int]:
    entries: dict[str, int] = {}
    for path in sorted(GAS_DIR.glob("*/*.snap")):
        for line in path.read_text().splitlines():
            if line and not line.startswith("#"):
                name, value = line.rsplit(" ", 1)
                entries[name] = int(value)
    return entries


def write_snapshot(gas: dict[str, int], only_present: bool) -> list[Path]:
    by_file: dict[Path, dict[str, int]] = {}
    for name, value in gas.items():
        crate, module = module_of(name)
        by_file.setdefault(GAS_DIR / crate / f"{module}.snap", {})[name] = value
    if not only_present:
        for stale in GAS_DIR.glob("*/*.snap"):
            if stale not in by_file:
                stale.unlink()
    for path, entries in by_file.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER + "".join(f"{n} {entries[n]}\n" for n in sorted(entries)))
    return sorted(by_file)


def delta_rows(old: dict[str, int], new: dict[str, int]) -> list[tuple[str, str, str, str]]:
    rows = []
    for name in sorted(old.keys() | new.keys()):
        before, after = old.get(name), new.get(name)
        if before == after:
            continue
        if before is None:
            rows.append((name, "-", str(after), "new"))
        elif after is None:
            rows.append((name, str(before), "-", "removed"))
        else:
            pct = (after - before) / before * 100 if before else 0.0
            rows.append((name, str(before), str(after), f"{after - before:+d} ({pct:+.2f}%)"))
    return rows


def print_table(rows: list[tuple[str, ...]], headers: tuple[str, ...]) -> None:
    print("| " + " | ".join(headers) + " |")
    print("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        print("| " + " | ".join(row) + " |")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["snapshot", "check", "diff", "rank"])
    parser.add_argument("prefix", nargs="?", help="test-name prefix for `rank`")
    parser.add_argument("--from-log", type=Path)
    parser.add_argument("--filter")
    args = parser.parse_args()

    if args.command == "rank":
        entries = {k: v for k, v in load_snapshot().items() if (args.prefix or "") in k}
        ranked = sorted(entries.items(), key=lambda kv: kv[1])
        print_table([(name, str(value)) for name, value in ranked], ("test", "l2_gas"))
        return

    log = args.from_log.read_text() if args.from_log else run_tests(args.filter)
    new = parse(log)
    if not new:
        sys.exit("error: no test result found in snforge output")
    old = load_snapshot()

    if args.command == "snapshot":
        if args.filter:
            touched = {module_of(n) for n in new}
            kept = {n: v for n, v in old.items() if module_of(n) in touched and args.filter not in n}
            new = {**kept, **new}
        files = write_snapshot(new, only_present=bool(args.filter))
        print(f"wrote {len(new)} entries to {len(files)} file(s) under {GAS_DIR.relative_to(ROOT)}/")
        return

    if args.filter:
        old = {k: v for k, v in old.items() if args.filter in k}
    rows = delta_rows(old, new)
    if rows:
        print_table(rows, ("test", "before", "after", "delta"))
    else:
        print(f"gas snapshot up to date ({len(new)} tests)")
    if args.command == "check" and rows:
        sys.exit("error: gas usage drifted from gas/*.snap; run `scripts/gas.py snapshot` and commit the result")


if __name__ == "__main__":
    main()
